// Arduino / FastLED sketch exporter.
//
// Produces a compilable .ino sketch for one ESP32 (or equivalent) per
// FastLED controller in the topology. Each sketch wires up:
//   - per-output CRGB buffers on the correct pins with each output's own
//     chipset from the topology,
//   - the gamma LUT that matches the simulator's color pipeline,
//   - the color-order template param on `FastLED.addLeds<>`,
//   - master brightness matching the sim's brightness slider,
//   - a small rainbow demo in loop() as a "the wiring works" smoke test.
//
// The pattern itself isn't transpiled — patterns are authored in JS against
// the simulator's runtime and baked to frames via wledBaked.ts, or the
// user hand-ports them into the loop() body once the topology and gamma
// plumbing is correct.

import type { Topology, Controller } from '../topology';
import type { ColorConfig } from '../colorSpace';
import { gammaLut } from '../colorSpace';

export type FastLedSketchFile = {
  filename: string;
  code: string;
};

// Render a 256-entry gamma LUT as a PROGMEM array literal, 16 values per
// line for legibility.
function renderLut(lut: Uint8Array): string {
  const lines: string[] = [];
  for (let i = 0; i < 256; i += 16) {
    const chunk = Array.from(lut.slice(i, i + 16))
      .map((v) => String(v).padStart(3, ' '))
      .join(', ');
    lines.push('  ' + chunk + (i + 16 < 256 ? ',' : ''));
  }
  return lines.join('\n');
}

function renderOneController(
  ctrl: Controller,
  cfg: ColorConfig,
  gammaByte: Uint8Array,
): string {
  const bri = Math.round(Math.max(0, Math.min(1, cfg.brightness)) * 255);
  const order = cfg.colorOrder; // FastLED accepts RGB/RBG/GRB/GBR/BRG/BGR directly

  const outputDecls = ctrl.outputs
    .map(
      (o, i) =>
        `CRGB leds_${i}[${Math.max(1, o.ledCount)}];  // pin ${o.pin} — ${o.label} (${o.chipset})`,
    )
    .join('\n');

  // Each output drives whatever chipset the topology says is on it — a rib
  // channel strip and its hole-LED chain are usually different stock (e.g.
  // WS2815 strip + discrete WS2811 pixels). FastLED's chipset identifiers
  // match our Chipset union directly; recent FastLED (3.6+) has WS2815.
  const addLedsCalls = ctrl.outputs
    .map(
      (o, i) =>
        `  FastLED.addLeds<${o.chipset}, ${o.pin}, ${order}>(leds_${i}, ${o.ledCount});`,
    )
    .join('\n');

  const demoLoops = ctrl.outputs
    .map(
      (_, i) => `  for (uint16_t i = 0; i < sizeof(leds_${i}) / sizeof(leds_${i}[0]); i++) {
    leds_${i}[i] = gammaCorrect(CHSV(hue + i, 255, 200));
  }`,
    )
    .join('\n');

  const totalLeds = ctrl.outputs.reduce((n, o) => n + o.ledCount, 0);

  return `// Auto-generated by Orbiter. Do not hand-edit — re-export instead.
// Controller: ${ctrl.name} (${ctrl.host || 'serial/direct'})
// Outputs: ${ctrl.outputs.length} · Total LEDs: ${totalLeds}
// Gamma: ${cfg.gamma} · Brightness: ${bri}/255 · Color order: ${order}

#include <FastLED.h>

${outputDecls}

// Gamma LUT (matches Orbiter's simulator pipeline at gamma=${cfg.gamma}).
const uint8_t GAMMA_LUT[256] PROGMEM = {
${renderLut(gammaByte)}
};

static inline CRGB gammaCorrect(CRGB c) {
  return CRGB(
    pgm_read_byte(&GAMMA_LUT[c.r]),
    pgm_read_byte(&GAMMA_LUT[c.g]),
    pgm_read_byte(&GAMMA_LUT[c.b])
  );
}

void setup() {
${addLedsCalls}
  FastLED.setBrightness(${bri});
  FastLED.setDither(BINARY_DITHER);
}

void loop() {
  // ---- USER PATTERN ----
  // Placeholder demo: slow full-chain rainbow. Replace with the C++ port
  // of your Orbiter pattern (or stream frames in from the baked JSON).
  uint32_t now = millis();
  uint8_t hue = (uint8_t)((now / 30) & 0xFF);

${demoLoops}

  FastLED.show();
  FastLED.delay(16);  // ~60 fps
}
`;
}

// Emits one sketch per FastLED controller. Controllers of kind 'WLED' are
// skipped — they use the preset / baked exporters instead. Returns an
// empty array when no FastLED controllers exist (caller should surface
// this to the UI rather than throw, since a topology with only WLED is a
// common valid state).
export function buildFastLedSketches(
  topology: Topology,
  cfg: ColorConfig,
): FastLedSketchFile[] {
  const gammaByte = gammaLut(cfg.gamma);
  const files: FastLedSketchFile[] = [];
  for (const c of topology.controllers) {
    if (c.kind !== 'FastLED') continue;
    const safeName = c.name.replace(/[^a-zA-Z0-9_-]/g, '_');
    files.push({
      filename: `${safeName}.ino`,
      code: renderOneController(c, cfg, gammaByte),
    });
  }
  return files;
}
